# Generated by Django 6.0.1 on 2026-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_auth_id_alter_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='agenda',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
