# Generated by Django 6.0.1 on 2026-01-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_agenda_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
