# Generated by Django 6.0.1 on 2026-01-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booked_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
